import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";

import LeftMenu from "@/components/leftMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-orbitron',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased`}
        style={{ 
          fontFamily: 'var(--font-orbitron)',
          backgroundImage: "url('/BG.png')",
          backgroundSize: "cover",
          backgroundPosition: "left"
        }}
      >
        <div className="flex h-screen md:mx-10">
          <LeftMenu />
          <div className="flex-1 w-100 px-10 md:px-20 my-10 pb-15 md:pb-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
